#!/usr/bin/env sh
HELP() {
echo "Usage : ./install-script action=[action] (var=val)"
echo "Actions:"
echo "HELP                Print this message"
echo "CHECK               Check for commands"
echo "COMPILE             Compile source code"
echo "INSTALL             Install package"
echo "CLEAN               Clean current build"
echo "INSTALL_MIRROR      Install available mirrors"
echo "If \$action is empty, it will run COMPILE by default"
echo "Build variables:"
echo "CC=<binary>         C compiler (default clang, need a linker)"
echo "CFLAGS=<flags>      C compiler flags (-fuse-ld=<linker> to change linker)"
echo "PREFIX=<dir>        Install prefix (default /usr/local)"
echo "DESTDIR=<dir>       Install directory (default /)"
echo "SYSROOT=<dir>       Package root directory (default /)"
echo "CONFDIR=<dir>       Package config directory (default \$SYSROOT/etc)"
echo "Options:"
echo "keepcfg=<val>       Keep old config"
echo "verbose=<val>       Verbose"
echo "You can create a .config file so that it will be used for compilation"
exit
}

msg() {
if test -z "$verbose" ; then
	echo $*
fi
}

run() {
msg $* 
$* 
}

CHECK() {
COMMAND="install sed rm echo tee \
	find tar gzip mkdir cat \
	diff ln readlink sh $CC"
for x in "$COMMAND"; do
	if ! command -v $x > /dev/null 2>&1; then
		msg "Check if $x is available"
		echo "$x is not found."
	fi
done
}


COMPILE() {
run cp -r src/* out/ 
run cp -r etc/*.conf out/ 
run cp -r scripts/* out/

run sed "s|SYSROOT|$SYSROOT|g" -i out/hanh.conf out/hanhbuild.conf
run sed "s|CONFDIR|$CONFDIR|g" -i out/hanh.conf out/hanhbuild out/hanh.c out/hanhbuild.conf out/genpkg
run sed "s|prefix|$PREFIX|g" -i out/hanh.c
cd out/
CC=$CC CFLAGS="$CFLAGS" ./build 
cd ../ 
}

INSTALL() {
run install -dm755 $DESTDIR/$SYSROOT/$PREFIX/bin/
run install -dm755 $DESTDIR/$SYSROOT/$PREFIX/include/
run install -dm755 $DESTDIR/$SYSROOT/var/lib/pachanh/system
run install -dm755 $DESTDIR/$SYSROOT/var/lib/pachanh/remote
run install -dm755 $DESTDIR/$CONFDIR/hanh.d

run install -Dm755 out/hanh $DESTDIR/$SYSROOT/$PREFIX/bin/hanh 
run install -Dm755 out/hanhbuild $DESTDIR/$SYSROOT/$PREFIX/bin/hanhbuild
run install -Dm755 out/genpkg $DESTDIR/$SYSROOT/$PREFIX/bin/genpkg

run install -Dm644 src/hanh.h $DESTDIR/$SYSROOT/$PREFIX/include/hanh.h

if test -z "$keepcfg"; then
	run install -Dm644 out/hanh.conf $DESTDIR/$CONFDIR/hanh.conf
	run install -Dm644 out/hanhbuild.conf $DESTDIR/$CONFDIR/hanhbuild.conf
fi

for dir in $etcdirs; do
	run install -dm755 $DESTDIR/$CONFDIR/hanh.d/$dir 
	for f in $(ls etc/$dir); do 
		run install -Dm644 etc/$dir/$f $DESTDIR/$CONFDIR/hanh.d/$dir/$f 
	done
done
}

CLEAN() {
run rm -rf out
run mkdir out
}

eval "$*"

if test -f config; then
	. config || exit 1
fi

if test -z "$CC"; then
	CC=clang
fi

if test -z "$PREFIX"; then
	PREFIX="/usr/local"
fi

if test -z "$SYSROOT"; then
	SYSROOT="/"
fi

if test -z "$CONFDIR"; then
	CONFDIR="$SYSROOT/etc"
fi

if test -z "$cfgdirs"; then 
	etcdirs="mirror profile"
fi

if test -z "$action"; then
	action="COMPILE"
fi

$action || echo "Failed to run function $action" && exit 1
