#!/bin/sh
. "CONFDIR/hanh.d/functions" || die "Cannot get functions from file"
if test -z "$GEN"; then 
	echo "This part is from hanhbuild script"
	echo "It doesn't do anything without hanhbuild"
	exit 
fi

. "${1}" || die Cannot get information from build file

eval $2 $misc
