#!/bin/sh
version=2.0
remote=/var/lib/pachanh/remote
system=/var/lib/pachanh/system

print_help() {
echo "hanhbuild - Hanh Linux packages builder"
echo "Usage: hanhbuild [Action] [Options]"
echo "Action:"
echo "-h                           Print this message"
echo "-v                           Print version"
echo "-g                           Create database archive of all packages in current directory"
echo "-F                           Fetch package(s) build file(s)"
echo "-b                           Build packages"
echo "-gf                          See all available flags from a build file"
echo "Options:"
echo "-R=<path>                    Root directory <overwrite \$SYSROOT>"
echo "-bf=<path>                   Build file"
echo "Options <for build action only>:"
echo "-d                           Do not check dependencies"
echo "-c                           Clean build"
echo "-f                           Force"
echo "-bd                          Build dependencies"
echo "-t=[unpack,compile,mkpkg]    Build tasks"
echo "-i                           Install packages after build (skip compile if package found)"
echo "-s                           Compare system package version"
echo "-I                           Ignore error (if package not found)"
echo "Options <for database only>:"
echo "-r=<name>                    Repository name"
echo "-H=<path>                    Hook script"
exit 0
}
err() {
echo "ERROR: $*"
}

die() {
err "$*"
exit 1
}

fetch() {
eval "$downloader $*" || die "Failed to fetch source"
}

fetch_pkg() {
cwd=$(pwd)
if test -z "$repo"; then
	die "Empty repo"
fi

for x in $*; do
	unset fetched found
	for y in $repo; do
		if test -d $sysroot/$remote/$y/$x; then
			found=1
			for z in $(cat "$mirror/$y"); do
					fetch $z/$x/buildhanh
					if test -f "$(pwd)/buildhanh"; then
						fetched=1 
						. "$(pwd)/buildhanh"
						for t in $attach; do 
							fetch $z/$x/$t
						done
						cd $cwd
						break
					fi	
			done
		fi
	done
	if test -z $found; then 
		if test -z "$ignore"; then 
			die "Cannot find specified package ($x)"
		fi
	fi
done
}

compare_sysver() {
unset same initver version
if test -d $sysroot/$system/$name/info; then
	initver=$(cat $sysroot/$system/$name/info | grep version)
	version=$(echo $initver | cut -d "=" -f 2)

	if test "$ver" == "$version"; then 
		same=y
	fi
fi
}

check_deps() {
if test -n "$*"; then
	for dep in $*; do
		if ! test -d $sysroot/$system/$dep; then
			if test -z "$builddeps"; then
				die "Dependency $dep not found"
			else
				cd "$hanhdir"/deps
				hanhbuild -F "$dep" || die 
				cd "$dep"
				hanhbuild -b -bd || die "Failed to build dependencies"
				hanh -i $dep*.hanhpkg.tar.xz || die "Failed to install dependencies"
				cd "$hanhdir"
			fi
		fi
	done
fi
}

check_files() {
for x in $*; do
	if ! test -f "$hanhdir"/"$x"; then 
		die "$x not found!"
	fi
done
}

check_contain() {
cd $pkgdir/$system
for x in $*; do
	ln -sf "$name" "$x" 
done
cd $pkgdir
}

check_config() {
for x in $*; do 
	mv "$pkgdir"/"$x" "$pkgdir"/"$x".newfile
done
}

get_flag() {
if test -z "$buildfile"; then
	buildfile="$(pwd)/buildhanh"
fi
. "$buildfile" || die "Cannot get build information from $buildfile"
echo "Build flavor are: $buildFlavor"
echo "Build flags are: $buildFlags"
}

gen_db() {
. $buildfile || die
echo "$name-$ver" > data
echo "$desc" >> data
}

gen_archive() {
cwd=$(pwd)
test -z $dbrepo && die "Empty database repository name"
if test "$dbrepo" != "$(basename $dbrepo)"; then 
	echo "WARNING: database archive will be placed in $cwd/$(basename $dbrepo).database"
	dbrepo=$(basename $dbrepo) 
fi 

rm -rf $dbrepo && mkdir $dbrepo
for pkgdir in $(ls); do  
	if test "$pkgdir" != "$dbrepo"; then  
		mkdir $cwd/$dbrepo/$pkgdir 
		cd $cwd/$pkgdir 
		buildfile=$cwd/$pkgdir/buildhanh gen_db
		mv data $cwd/$dbrepo/$pkgdir/ 
		cd ..
	fi
done

cd $dbrepo 
install -Dm755 $hook .
tar -cJf $cwd/$dbrepo.database *
}

gen_info() {
info="${1}"
echo "name=\"$name\"" >> "$info"
echo "version=\"$ver\"" >> "$info"
echo "desc=\"$desc\"" >> "$info"
echo "home=\"$home\"" >> "$info"
echo "license=\"$license\"" >> $info
echo "depends=\"$depends\"" >> "$info"
echo "contain=\"$contain\"" >> "$info"
echo "dependants=\"\"" >> "$info"
}

gen_filelist() {
FILELIST="${1}"
cd "${pkgdir}"
find * | tee "$FILELIST" > /dev/null 2>&1
}

gen_header() {
HEADER="${1}"
echo "name=\"$name\"" >> "$HEADER"
echo "version=\"$ver\"" >> "$HEADER"
echo "desc=\"$desc\"" >> "$HEADER"
echo "depends=\"$depends\"" >> "$HEADER"
echo "contain=\"$contain\"" >> "$HEADER"
echo "config=\"$config\"" >> "$HEADER"
echo "pkg_infodir=\"var/lib/pachanh/system/$name\"" >> "$HEADER"
}

ask() {
cwd=$(pwd)
read -r package
pkg=$(echo $package | cut -d " " -f 1)
for x in $*; do
	if test "$pkg" = "$x"; then
		found=1
		mkdir -p asked
		cd asked
		if test "$pkg" != "$name"; then
			fetch_pkg $pkg
			cd $pkg
			hanhbuild -b $misc || exit 1
		else
			echo "Building the package with the same name"
			hanhbuild -bf=$hanhdir/buildhanh.$name -b $misc || exit 1
		fi

		mv *hanhpkg* $cwd
		cd $cwd

	fi
done

if test -z $found; then
	echo "Package name $package not found! Re-enter again"
	ask $*
fi
}

ask_pkg() {
echo "Available packages are: $*"
echo "Please enter one below"
ask $*
}

define_ask() {
ver=9999
desc="Ask for $name providers"
task="pkgask"
}

build() {
test -n "$USE_FLAGS" && export $USE_FLAGS
. "$buildfile" || die "Cannot get information from $buildfile"

if test -n "$Task"; then
	task="$Task"
fi

cd $hanhdir

tarball="$name"-"$ver".hanhpkg.tar.xz

if test -n "$syscompare"; then 
	compare_sysver $name 
	if test -n "$same"; then 
		echo "$name is up-to-date."
		exit 
	fi
fi

if test -f "$hanhdir"/"$tarball"; then 
	if test -z "$force"; then 
		# This won't be listed as error 
		echo "WARNING: Package built."
		test -z $install && exit 0
	else 
		unset install
	fi

	if test -n "$install"; then
		hanh -i "$hanhdir"/"$tarball"
		exit 0
	fi
fi

if test -n "$clean"; then
	rm -rf "$pkgdir" "$workdir" "$hanhdir"/.buildinfo "$hanhdir"/"$tarball" "$hanhdir"/deps
fi

rm -rf "$pkgdir"
mkdir -p "$pkgdir" "$workdir"

if test -f "$hanhdir"/.buildinfo; then 	
	. "$hanhdir"/.buildinfo || die "Failed to run .buildinfo"
fi

if test -z "$task"; then
	task="unpack compile mkpkg" 
fi

if test -z "$nodeps"; then	
	echo "Checking deps..."
	mkdir -p $hanhdir/deps
	check_deps $depends $mkdeps  
fi

echo "Fetching sources..."
for url in $sources; do
	fetch $url || die "Failed to fetch sources"
done

check_files $files 

for func in $task; do 
	unset run_compile
	echo "Running function $func..."
	if test "$func" = "compile"; then
		run_compile=1
		if test -n "$flavor"; then
			for flv in $flavor; do 
				if test -n "$(type compile_$flv | grep function)"; then
					echo "Using flavor $flv to build."
					use_flavor=1
					echo "used=$flv" >> $hanhdir/.buildinfo
					eval compile_$flv || die "Failed to run function compile_$flv"
					break
				fi
			done
			if test -z $use_flavor; then 
				echo "No specfied build flavor found! Using compile by default..."
				eval compile || die "Failed to run function compile"
			fi
		else
			eval compile || die "Failed to run function compile"
		fi
	fi

	if test -z $run_compile; then 
		eval "$func" || die "Failed to run function $func"
	fi

	if test "$func" = "mkpkg"; then
		repack=1;
	fi
done

if test -n "$repack"; then
	cd $pkgdir
	infodir=$pkgdir/var/lib/pachanh/system/"$name"
	mkdir -p "$infodir"

	check_contain $contain
	check_config  $config
	
	touch "$infodir"/filelist
	gen_info "$infodir"/info
	gen_header "$pkgdir"/pre-install
	gen_filelist "$infodir"/filelist
	if test -f "$hanhdir"/"$hook"; then 
		install -Dm755 "$hanhdir"/"$hook" "$pkgdir"/hook
		install -Dm755 "$hanhdir"/"$hook" "$infodir"/hook
	fi
	
	cd "$pkgdir"
	tar -cJf "$hanhdir"/"$tarball" *	
	echo "Package $tarball created."
	if test -n "$install"; then 
		hanh -i $hanhdir/$name-$ver.hanhpkg.tar.xz 
	fi
fi
} 

. CONFDIR/hanhbuild.conf || die "Cannot get information from configuration file."

for arg in $*; do
	case $arg in 
		-h) print_help;;
		-v) echo "$version";exit;;
		-d) export nodeps=1;;
		-f) export force=1;;
		-c) export clean=1;;
		-i) export install=1;;
		-s) export syscompare=1;;
		-bd) export builddeps=1;;
		-R=*) sysroot="$(echo $arg | cut -d "=" -f 2)";;
		-bf=*) buildfile="$(echo $arg | cut -d "=" -f 2)";;
		-t=*) Task="$(echo $arg | cut -d "=" -f 2 | sed 's/,/ /g')";;
		-fl=*) flag="$(echo $arg | cut -d "=" -f 2)";;
		-r=*) export dbrepo="$(echo $arg | cut -d "=" -f 2)";;
		-H=*) export hook="$(echo $arg | cut -d "=" -f 2)";;
		-b) action=build;;
		-F) action=fetch_pkg;;
		-g) action=gen_archive;;
		-gf) action=get_flag;;
		*) misc="$misc $arg";;
	esac
done

if test -z "$buildfile"; then
	buildfile="$hanhdir/buildhanh"
fi

$action $misc
