#!/bin/sh

. CONFDIR/hanhbuild.conf || die "Cannot get information from configuration file."
. CONFDIR/hanh.d/functions || die "Cannot get functions from file"
downloader="$download"

for arg in $*; do
	case $arg in 
		-h) print_help;;
		-v) echo "$version";exit;;
		-d) export nodeps=1;;
		-f) export force=1;;
		-c) export clean=1;;
		-i) export install=1;;
		-s) export syscompare=1;;
		-bd) export builddeps=1;;
		-S) export stagemode=1;;
		-R=*) export sysroot="$(echo $arg | cut -d "=" -f 2)";;
		-bf=*) export buildfile="$(echo $arg | cut -d "=" -f 2)";;
		-t=*) export Task="$(echo $arg | cut -d "=" -f 2 | sed 's/,/ /g')";;
		-fl=*) export flag="$(echo $arg | cut -d "=" -f 2)";;
		-ir=*) export installRoot=$(echo $arg | cut -d "=" -f 2);;
		-r=*) export dbrepo="$(echo $arg | cut -d "=" -f 2)";;
		-H=*) export repohook="$(echo $arg | cut -d "=" -f 2)";;
		-a*) compile_flags="$compile_flags $arg";;
		-b) action=build;;
		-F) action=fetch_pkg;;
		-g) action=gen_archive;;
		-gi) action=get_info;;
		-gf) action=get_flag;;
		-gt) action=get_tarball;;
		-gn) action=get_info;;
		*) misc="$misc $arg";;
	esac
done

if test "$nodeps" == 1; then
	echo "WARNING: Overwrites build dependencies to no because no dependencies build set"
	unset builddeps
fi

if test -z "$buildfile"; then
	buildfile="$hanhdir/buildhanh"
else 
	cd $(dirname $buildfile)
	hanhdir="$(pwd)"
	sourcedir="$hanhdir/sources"
	workdir="$hanhdir/work"
	pkgdir="$hanhdir/pkg"
fi

if test -n "$compile_flags"; then
	append_compileflags $compile_flags
fi

$action $misc
