#!/bin/sh
version=2.0 
system=/var/lib/pachanh/system
remote=/var/lib/pachanh/remote

die() {
echo ERROR: $* 
exit 1
}
help() {
echo "update_pkg - Update packages stuff"
echo "Usage: update_pkg [action]"
echo "Action: "
echo "-update-bad         Update bad list packages"
echo "-v                  Print version"
echo "-h                  Print help message" 
exit 0
}

print_ver() {
echo $version
exit 0
}

update_bad_list() {
rm -rf $SYSROOT/$remote/packages.*
for T in $TYPE; do 
	echo "Updating $T packages..."
	for file in $(find $SYSROOT/$remote/*/*.$T); do 
		cat $file >> $SYSROOT/$remote/packages.$T || die "Cannot update $T packages"
	done
done
}

. CONFDIR/hanh.conf || die "Cannot get information from configuration file."

for arg in $*; do
	case $arg in 
		-update-bad ) action=update_bad_list;;
		-v )          action=print_ver;;
		-h )          action=help;;
	esac
done

$action 
